---
title: "My Fisheries Analysis"
author: "Connor"
date: "1/28/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
library(tidyverse)
library(here)  
library(janitor) 
library(paletteer) # install.packages("paletteer")

```

```{r}
us_landings <- read_csv(here("data", "noaa_landings.csv"), 
                        na = "no data")
salmon_clean <- (us_landings %>% 
  clean_names() %>% 
  mutate(afs_name = str_to_lower(afs_name)) %>% 
  mutate(dollars_num = parse_number(dollars_usd)) %>% 
    filter(str_detect(afs_name, pattern = "salmon")) %>% 
    separate( afs_name, into = c("salmon_group", "sub_group"), sep = ", ") %>% 
    drop_na(dollars_num))
```

### Annual total value by salmon subgroup

```{r}
salmon_us_annual <- salmon_clean %>% 
  group_by(year, sub_group) %>% 
  summarize(
    tot_value = sum(dollars_num, na.rm = TRUE)
  )

```

### Line graph of salmon

```{r}
ggplot(data = salmon_us_annual, aes(x = year, y = tot_value, group = sub_group)) +
  geom_line(aes(color = sub_group)) + theme_bw() +
  labs(x = "Year", y = "US commercial salmon value (USD)", title = "US Salmon") +
  scale_color_paletteer_d("palettetown::parasect")
```

